apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: {{ .Values.deployment.namespace }}
  labels:
    app: {{ .Values.deployment.app }}
    release: "{{ .Release.Revision }}"
spec:
  replicas: {{ .Values.deployment.replicas}}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.deployment.app }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.deployment.app }}
    spec:
      restartPolicy: Always
      containers:
      - name: {{ .Values.deployment.app }}
        imagePullPolicy: Always
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.version }}
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: http
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz/live
            port: http
          initialDelaySeconds: 1
          periodSeconds: 10
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 100m
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: CONNECTIONSTRINGS_PGCONNECTION
          value: "{{ .Values.env.CONNECTIONSTRINS_PGCONNECTION}}"
    
