apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-api
  namespace: {{ .Values.deployment.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: weather.example
    http: 
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-api
            port:
              number: {{ .Values.service.port }}