apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.app }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{ .Values.deployment.app }}
  type: ClusterIP